### ISSUE TITLE
Where can I find the used keywords (total 760) and splits from the paper?

### ISSUE THREAD

**Issue by V0XNIHILI** [harvard-edge/multilingual_kws#41]
**First of all, thanks a lot for this work! It is incredibly useful for training strong models for keyword spotting.**

I would like to train with the same data as mentioned in the paper: where can I download this data or where can I download a list of the files used for training/validation/testing etc. (see image below for the dataset I am looking for0?

<img width="428" alt="image" src="https://user-images.githubusercontent.com/24796206/229296365-ea396ea9-f293-4587-951c-2426591dad3a.png">

For example, the newest version of the dataset on mlcommons.org has now more than 340k keywords:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/24796206/229296245-01b9ac97-08b4-49c3-832e-062f54260643.png">

So is there such an overview somewhere? I couldnt find it on the mlcommons website or in this repo, but maybe I missed it somewhere.

**Comment by V0XNIHILI** [comment]
@mmaz could you help me out with this? Many thanks in advance!

**Comment by mmaz** [comment]
Hi, the list of samples used in the interspeech paper is not publicly archived, only the model weights and code are released. However, a similar set of samples can be selected from MSWC by following the per-language sample counts provided in the interspeech paper, and the MSWC alignments can be used to extract samples padded with contextual audio instead of silence from the original Common Voice data.

**Comment by V0XNIHILI** [comment]
Thanks for the clarification!
